baseurl: https://pvillela.github.io/blog
title: Paulo Villela
theme: ghostwriter
languageCode: en-us
copyright: Paulo Villela - All rights reserved
googleAnalytics: XXX
canonifyurls: true

params:
  mainSections:
    - post
  intro: true
  headline: Paulo Villela
  description: Thoughts on Software Architecture and Engineering
  github: "https://github.com/pvillela"
  linkedin: https://linkedin.com/in/pvillela/
#  email: xxx@example.com
  opengraph: true
  shareTwitter: false
  dateFormat: "Mon, Jan 2, 2006"

permalinks:
  post: "/:year/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    # - name: Projects
    #   url: /project/
    #   weight: 2
    - name: Contact
      url: /page/contact/
      weight: 3
    - name: About
      url: /page/about/
      weight: 4
